# assumes outputs generated by gen.sh using optseq2 
# (in folder par, etc)
#

import os
import sys
import csv

def parse(fname):
    duration = []
    start = []
    stim = []
    with open(fname) as f:
        reader = csv.reader(f, delimiter=' ')
        for row in reader:
            row = filter(None, row)
            start.append(float(row[0]))
            duration.append(float(row[2]))
            stim.append(row[4])
    jitter = duration[1::2]
    stimTime = duration[0::2]
    start = start[0::2]
    stim = stim[0::2]
    assert len(stimTime) == len(stim)

    choice = []
    off = []
    cueId = []
    contextId = []
    t = 0
    for i in range(len(stimTime)):
        choice.append(t)
        t += stimTime[i]
        off.append(t)
        t += jitter[i]

        stim_i = stim[i].lower()
        if 'x1' in stim_i:
            cueId.append(0)
        elif 'x2' in stim_i:
            cueId.append(1)
        else:
            assert 'x3' in stim_i
            cueId.append(2)

        if 'c1' in stim_i:
            contextId.append(0)
        elif 'c2' in stim_i:
            contextId.append(1)
        else:
            assert 'c3' in stim_i
            contextId.append(2)
    assert choice == start, " wtf " + str(choice) + " vs " + str(start)


    #print choice
    #print off
    #print jitter
    #print stimTime
    #print stim
    return choice, off, jitter, stimTime, stim, cueId, contextId


if __name__ == "__main__":
    pars = os.listdir("par")

    train = []
    test = []

    for fname in pars:
        if fname.endswith('.par'):
            print fname
            x = parse(os.path.join("par", fname))
            if fname.startswith('itis_test'):
                test.append(x)
            else:
                train.append(x)

    next_train_idx = 0
    next_test_idx = 0
    # this is the file we potentially give to katie to analyze our stuff
    # note that this format is wrong -- her script requires a different format
    # but that's okay b/c we don't really need her analysis right now
    #
    with open('for_katie.csv', 'w') as f:
        cols = ['Subject', 'Run', 'Trial', 'Choice', 'Off', 'Jitter', 'StimTime', 'cueId', 'contextId']
        f.write(','.join(cols) + '\n')
        for subj in range(30):
            for run in range(9):
                # write it out the itis for each subject for each run in a separate file
                # this is crucial for psychopy to work in fMRI mode -- it reads the itis from here
                # format = trial # (0-based), jitter (in s), cueId (0-based), contextId (0-based)
                # this is parsed in the psychopy file, in new_run routine, in shuffleRestaurantsAndFoods code block
                #
                itis_file = os.path.join('csv', 'conP%03d_run%d_itis.csv' % (subj, run))
                with open(itis_file, 'w') as itif:
                    itif.write(','.join(['trialN', 'itiTime', 'cueId', 'contextId']) + '\n')

                    # write training trials
                    #
                    choice, off, jitter, stimTime, stim, cueId, contextId = train[next_train_idx]
                    for i in range(20):
                        row = [subj + 1, run + 1, i + 1, choice[i], off[i], jitter[i], stimTime[i], stim[i], cueId[i], contextId[i]]
                        f.write(','.join(str(x) for x in row) + '\n')
                        itif.write(','.join(str(x) for x in [i, jitter[i], cueId[i], contextId[i]]) + '\n')
                    next_train_idx += 1
                   
                    # write test trials
                    #   
                    t = off[-1] + jitter[-1] # starting point for test trials
                    choice, off, jitter, stimTime, stim, cueId, contextId = test[next_test_idx]
                    for i in range(4):
                        row = [subj + 1, run + 1, i + 20 + 1, choice[i] + t, off[i] + t, jitter[i], stimTime[i], stim[i], cueId[i], contextId[i]]
                        f.write(','.join(str(x) for x in row) + '\n')
                        itif.write(','.join(str(x) for x in [i + 20, jitter[i], cueId[i], contextId[i]]) + '\n')
                    next_test_idx += 1
